server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop?serverTimezone=UTC
    username: root
    password: 1234
  mail:
    host: smtp.naver.com
    port: 465
    username: bubbleland13@naver.com
    password: anehrkalswhd!12
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.ssl.trust: smtp.naver.com
      mail.smtp.starttls.enable: true
  jpa:
   hibernate:
      ddl-auto: update #테이블 생성
  properties:
    .hibernate:
      show_sql: true
      format_sql : true
      database-platform=org:
        hibernate:
          dialect:
            MySQL8Dialect:
  servlet:
    multipart:
      max-file-size: 20MB #파일 한개당 최대 사이즈
      max-request-size: 100MB #요청당 최대 파일 사이즈
  web:
    resources:
      static-locations: classpath:/static/

itemImgLocation: c:/shop/item
uploadPath: file:///C:/shop

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

  data:
    redis:
    host: localhost      # Redis 호스트 주소
    port: 6379

coolsms:
  api:
    key: "NCSGFAJS7KL9OT9E"       # CoolSMS API Key
    secret: "JHAQPQNBCWDZ71LWAPKLDDUQWQ9RLUOF" # CoolSMS API Secret
    number: "01084971811" # 발신자 번호 (인증된 번호여야 함)
